"""
End-to-End Integration Tests — Synthetic Data Pipeline
=======================================================

These tests exercise the full cloud-safe pipeline using only synthetic data
generated by :class:`~dsa110_continuum.simulation.harness.SimulationHarness`.
No CASA, no H17, no real HDF5 files are required.

Pipeline stages exercised
--------------------------
1. Synthetic data generation — ``SimulationHarness`` → UVH5 files
2. Geometry validation — UVW plausibility checks from UVH5
3. Frequency coverage — all 16 subbands span the correct range
4. Closure-relation integrity — per-subband noiseless closure ≈ 0°
5. Visibility statistics — noise floor and dynamic range
6. Sky-model fidelity — injected flux appears at correct amplitude
7. Multi-subband spectral consistency — spectral index preserved
8. Simulation metrics — flux recovery, astrometric offset helpers

Design principles
-----------------
* Every test is self-contained: it generates its own synthetic data and
  does not depend on shared mutable state.
* Tests use small arrays (4–8 antennas, 2–4 integrations) for speed.
* Expensive tests (all 16 subbands, full-resolution) are marked
  ``@pytest.mark.slow`` and skipped in normal CI unless ``--run-slow``
  is passed.
"""
from __future__ import annotations

import pathlib
import tempfile
from typing import Iterator

import numpy as np
import pytest

# ── skip guard ────────────────────────────────────────────────────────────────
pytest.importorskip("pyuvdata",   reason="pyuvdata not installed")
pytest.importorskip("pyradiosky", reason="pyradiosky not installed")

from dsa110_continuum.simulation.harness import (
    SimulationHarness,
    _FREQ_LOWER_EDGE_HZ,
    _CHAN_WIDTH_HZ,
    _N_SUBBANDS,
    _N_CHAN_PER_SB,
    _INTEGRATION_SEC,
)

# ── conftest-style helpers ────────────────────────────────────────────────────

def _make_small_harness(**kwargs) -> SimulationHarness:
    """Return a harness with fast-test defaults."""
    defaults = dict(n_antennas=6, n_integrations=3, n_sky_sources=8,
                    noise_jy=0.5, seed=42)
    defaults.update(kwargs)
    return SimulationHarness(**defaults)


# ── Stage 1: data generation ──────────────────────────────────────────────────

class TestStage1Generation:
    """Tests that the harness generates well-formed UVH5 files."""

    def test_single_subband_generates_file(self, tmp_path):
        h = _make_small_harness()
        p = tmp_path / "sb00.uvh5"
        out = h.generate_subband(0, p)
        assert out.exists()
        assert out.stat().st_size > 1024  # at least 1 kB

    def test_all_16_subbands_generated(self, tmp_path):
        """All 16 subbands should generate without error."""
        h = _make_small_harness(n_integrations=2)
        paths = h.generate_subbands(tmp_path, n_subbands=_N_SUBBANDS)
        assert len(paths) == _N_SUBBANDS
        for p in paths:
            assert p.exists()

    def test_generate_and_reload(self, tmp_path):
        """A generated UVH5 should be readable by pyuvdata."""
        from pyuvdata import UVData
        h = _make_small_harness(noise_jy=0.0)
        p = tmp_path / "reload.uvh5"
        h.generate_subband(4, p)
        uv = UVData()
        uv.read(str(p))
        assert uv.Nfreqs == _N_CHAN_PER_SB
        assert uv.Npols == 2

    def test_multiple_seeds_produce_different_data(self, tmp_path):
        h1 = _make_small_harness(seed=10)
        h2 = _make_small_harness(seed=20)
        p1 = tmp_path / "s10.uvh5"
        p2 = tmp_path / "s20.uvh5"
        h1.generate_subband(0, p1)
        h2.generate_subband(0, p2)
        uv1 = h1.load_subband(p1)
        uv2 = h2.load_subband(p2)
        assert not np.allclose(uv1.data_array, uv2.data_array)


# ── Stage 2: geometry validation ──────────────────────────────────────────────

class TestStage2Geometry:
    """UVW geometry checks from UVH5 data (no CASA required)."""

    def test_uvw_within_physical_limits(self, tmp_path):
        """Max baseline in simulation is ~980 m (east span).

        UVW magnitudes should not exceed the physical array size.
        We use 2× as a generous bound accounting for projection effects.
        """
        h = _make_small_harness(n_antennas=8)
        p = tmp_path / "geom.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)

        uvw_lengths = np.linalg.norm(uv.uvw_array, axis=1)
        max_obs = uvw_lengths.max()
        # DSA-110 max baseline ~2707 m; our simulated array spans ~980 m east
        # Projection can spread UVW, so allow 2 × physical span as upper bound
        assert max_obs < 5000.0, f"UVW length {max_obs:.1f} m exceeds 5000 m bound"

    def test_uvw_not_all_zeros(self, tmp_path):
        h = _make_small_harness()
        p = tmp_path / "nonzero.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        assert np.any(uv.uvw_array != 0.0)

    def test_uvw_shape(self, tmp_path):
        n_ants = 6; n_ints = 3
        h = _make_small_harness(n_antennas=n_ants, n_integrations=n_ints)
        p = tmp_path / "shape.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        n_bls = n_ants * (n_ants - 1) // 2
        assert uv.uvw_array.shape == (n_bls * n_ints, 3)

    def test_uvw_u_axis_dominant_for_ew_array(self, tmp_path):
        """DSA-110 is an E-W array → u-coverage should span a wide range.

        Note: with correct Earth-rotation-synthesis UVW (phased to the field
        centre), u and v both rotate with hour angle, so mean|u| > mean|v| does
        NOT hold in general.  Instead we verify that the u-axis spans a range
        consistent with the ~980 m E-W baseline extent at L-band.
        """
        h = _make_small_harness(n_antennas=8, noise_jy=0.0)
        p = tmp_path / "ew.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        # u-coverage range must be > 100 m (8 antennas over ~980 m baseline)
        u_range = uv.uvw_array[:, 0].max() - uv.uvw_array[:, 0].min()
        assert u_range > 100.0, (
            f"u-coverage range {u_range:.1f} m is too small for an 8-antenna E-W array. "
            "Expected > 100 m."
        )

    def test_integration_times_correct(self, tmp_path):
        h = _make_small_harness(n_integrations=4)
        p = tmp_path / "times.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        # integration_time should be exactly _INTEGRATION_SEC
        np.testing.assert_allclose(uv.integration_time, _INTEGRATION_SEC, rtol=1e-6)


# ── Stage 3: frequency coverage ───────────────────────────────────────────────

class TestStage3FrequencyCoverage:
    """Tests that all subbands together cover the full DSA-110 band."""

    def test_all_subbands_cover_full_band(self, tmp_path):
        """16 subbands should span 1311.25–1498.75 MHz (lower/upper edges)."""
        h = _make_small_harness(n_integrations=2)
        paths = h.generate_subbands(tmp_path, n_subbands=_N_SUBBANDS)

        all_freqs = []
        for p in paths:
            uv = h.load_subband(p)
            all_freqs.extend(uv.freq_array.tolist())

        all_freqs = np.array(sorted(set(all_freqs)))
        assert len(all_freqs) == _N_SUBBANDS * _N_CHAN_PER_SB, (
            f"Expected {_N_SUBBANDS * _N_CHAN_PER_SB} unique channels, "
            f"got {len(all_freqs)}"
        )

        # Band edges (channel centres): first centre = lower_edge + 0.5*chan
        expected_f_min = _FREQ_LOWER_EDGE_HZ + 0.5 * _CHAN_WIDTH_HZ
        expected_f_max = _FREQ_LOWER_EDGE_HZ + (_N_SUBBANDS * _N_CHAN_PER_SB - 0.5) * _CHAN_WIDTH_HZ
        np.testing.assert_allclose(all_freqs.min(), expected_f_min, rtol=1e-9)
        np.testing.assert_allclose(all_freqs.max(), expected_f_max, rtol=1e-9)

    def test_subbands_contiguous_no_gaps(self, tmp_path):
        """Adjacent subband frequencies should be separated by exactly one channel width."""
        h = _make_small_harness(n_integrations=2)
        paths = h.generate_subbands(tmp_path, n_subbands=_N_SUBBANDS)

        all_freqs = []
        for p in paths:
            uv = h.load_subband(p)
            all_freqs.extend(uv.freq_array.tolist())

        all_freqs = np.array(sorted(set(all_freqs)))
        gaps = np.diff(all_freqs)
        np.testing.assert_allclose(gaps, _CHAN_WIDTH_HZ, rtol=1e-9,
                                   err_msg="Frequency gaps between subbands are not uniform")

    def test_subband_indices_encode_frequency(self, tmp_path):
        """Higher subband index → higher frequency range."""
        h = _make_small_harness(n_integrations=2)
        f_mins = []
        for sb in range(4):
            p = tmp_path / f"sb{sb:02d}.uvh5"
            h.generate_subband(sb, p)
            uv = h.load_subband(p)
            f_mins.append(uv.freq_array.min())
        assert f_mins == sorted(f_mins), "Subband min-freqs should be monotonically increasing"

    def test_total_bandwidth(self, tmp_path):
        """Total bandwidth covered by all subbands should be exactly 187.5 MHz."""
        h = _make_small_harness(n_integrations=2)
        paths = h.generate_subbands(tmp_path, n_subbands=_N_SUBBANDS)

        all_freqs = []
        for p in paths:
            uv = h.load_subband(p)
            all_freqs.extend(uv.freq_array.tolist())

        all_freqs = sorted(set(all_freqs))
        # Bandwidth = (last channel upper edge) - (first channel lower edge)
        total_bw = (all_freqs[-1] + 0.5 * _CHAN_WIDTH_HZ) - (all_freqs[0] - 0.5 * _CHAN_WIDTH_HZ)
        np.testing.assert_allclose(total_bw / 1e6, 187.5, rtol=1e-6)


# ── Stage 4: closure-relation integrity ───────────────────────────────────────

class TestStage4ClosureIntegrity:
    """Tests that generated visibilities satisfy closure relations."""

    def test_closure_passes_all_subbands_fast(self, tmp_path):
        """Closure should pass for a representative subset of subbands."""
        h = _make_small_harness(n_antennas=6, n_integrations=2, noise_jy=0.0)
        for sb in [0, 4, 8, 15]:
            p = tmp_path / f"cl_sb{sb:02d}.uvh5"
            h.generate_subband(sb, p)
            result = h.check_closure(p, n_triangles=6)
            assert result["passed"], (
                f"Subband {sb} closure failed: max={result['max_closure_phase_deg']:.4f}°"
            )

    def test_closure_is_zero_for_phase_center_source(self, tmp_path):
        """Single source at phase centre → all closure phases exactly 0°."""
        import pyradiosky
        from astropy.coordinates import Longitude, Latitude
        from astropy.time import Time
        import astropy.units as u_

        h = _make_small_harness(n_antennas=5, n_integrations=2, noise_jy=0.0)
        stokes = np.zeros((4, 1, 1)); stokes[0, 0, 0] = 3.0
        sky = pyradiosky.SkyModel(
            name=["pc_src"],
            ra=Longitude([h.pointing_ra_deg] * u_.deg),
            dec=Latitude([h.pointing_dec_deg] * u_.deg),
            stokes=stokes * u_.Jy,
            spectral_type="spectral_index",
            spectral_index=np.array([0.0]),
            reference_frequency=np.array([1.4e9]) * u_.Hz,
            frame="icrs",
        )
        t0 = Time("2026-01-25T22:26:05", format="isot", scale="utc")
        uv = h._build_uvdata(0, t0, sky)

        n_bls = h.n_antennas * (h.n_antennas - 1) // 2
        ants_a = np.array([i for i in range(h.n_antennas) for j in range(i+1, h.n_antennas)])
        ants_b = np.array([j for i in range(h.n_antennas) for j in range(i+1, h.n_antennas)])

        def find_idx(a1, a2, t_idx):
            for k in range(len(ants_a)):
                if ants_a[k] == a1 and ants_b[k] == a2:
                    return t_idx * n_bls + k
            return None

        max_cl = 0.0
        for a, b, c in [(0, 1, 2), (0, 1, 3), (1, 2, 3), (0, 2, 3)]:
            i_ab = find_idx(a, b, 0)
            i_bc = find_idx(b, c, 0)
            i_ac = find_idx(a, c, 0)
            if None in (i_ab, i_bc, i_ac):
                continue
            v_ab = complex(uv.data_array[i_ab, 24, 0])
            v_bc = complex(uv.data_array[i_bc, 24, 0])
            v_ca = np.conj(complex(uv.data_array[i_ac, 24, 0]))
            cl = abs(float(np.degrees(np.angle(v_ab * v_bc * v_ca))))
            max_cl = max(max_cl, cl)

        assert max_cl < 1e-3, f"Closure phase for phase-centre source: {max_cl:.4f}°"

    def test_closure_noisy_check_uses_noiseless_internally(self, tmp_path):
        """check_closure should pass even when the UVH5 has high noise.

        The implementation builds a noiseless single-source UVData internally
        for the closure test, so the presence of noise in the file is irrelevant.
        """
        h = _make_small_harness(noise_jy=10.0, n_antennas=5)
        p = tmp_path / "noisy.uvh5"
        h.generate_subband(0, p)
        result = h.check_closure(p, n_triangles=5)
        assert result["passed"], (
            f"check_closure should pass for any noise level; got max={result['max_closure_phase_deg']:.4f}°"
        )


# ── Stage 5: visibility statistics ────────────────────────────────────────────

class TestStage5VisibilityStatistics:
    """Sanity checks on visibility amplitude and noise floor."""

    def test_noise_floor_scaling(self, tmp_path):
        """RMS of noise-only visibilities should scale with noise_jy."""
        h_lo = _make_small_harness(n_sky_sources=0, noise_jy=1.0)
        h_hi = _make_small_harness(n_sky_sources=0, noise_jy=5.0)

        # n_sky_sources=0 requires a manual sky (empty)
        import pyradiosky
        from astropy.coordinates import Longitude, Latitude
        from astropy.time import Time
        import astropy.units as u_
        import warnings

        stokes = np.zeros((4, 1, 1))  # zero-flux source — effectively noise-only
        sky = pyradiosky.SkyModel(
            name=["empty"],
            ra=Longitude([343.5] * u_.deg),
            dec=Latitude([16.15] * u_.deg),
            stokes=stokes * u_.Jy,
            spectral_type="spectral_index",
            spectral_index=np.array([0.0]),
            reference_frequency=np.array([1.4e9]) * u_.Hz,
            frame="icrs",
        )
        t0 = Time("2026-01-25T22:26:05", format="isot", scale="utc")

        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            uv_lo = h_lo._build_uvdata(0, t0, sky)
            uv_hi = h_hi._build_uvdata(0, t0, sky)

        rms_lo = float(np.std(uv_lo.data_array.real))
        rms_hi = float(np.std(uv_hi.data_array.real))
        ratio = rms_hi / rms_lo
        np.testing.assert_allclose(ratio, 5.0, rtol=0.2,
                                   err_msg=f"noise RMS ratio {ratio:.2f} not ~5.0")

    def test_dynamic_range_positive(self, tmp_path):
        """Dynamic range = max_amplitude / rms_noise should be > 1 for signal+noise."""
        h = _make_small_harness(noise_jy=0.5, n_sky_sources=10, n_antennas=8)
        p = tmp_path / "dr.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        amps = np.abs(uv.data_array[:, :, 0])
        dr = amps.max() / (amps.std() + 1e-30)
        assert dr > 1.0, f"Dynamic range {dr:.2f} not > 1"

    def test_flag_array_all_false(self, tmp_path):
        """Synthetic data should have no flags set."""
        h = _make_small_harness()
        p = tmp_path / "flags.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        assert not uv.flag_array.any()

    def test_nsample_array_positive(self, tmp_path):
        h = _make_small_harness()
        p = tmp_path / "nsamp.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        assert np.all(uv.nsample_array > 0)

    def test_data_array_finite(self, tmp_path):
        """No NaN or Inf should appear in the data array."""
        h = _make_small_harness()
        p = tmp_path / "finite.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        assert np.all(np.isfinite(uv.data_array.real))
        assert np.all(np.isfinite(uv.data_array.imag))


# ── Stage 6: sky-model fidelity ───────────────────────────────────────────────

class TestStage6SkyModelFidelity:
    """Tests that injected sources appear at the expected amplitude."""

    def test_single_source_amplitude_at_phase_center(self, tmp_path):
        """A single Stokes-I source of flux F_0 Jy at the phase centre should
        produce visibilities with |V_XX| = |V_YY| = F_0/2 everywhere.
        """
        import pyradiosky
        from astropy.coordinates import Longitude, Latitude
        from astropy.time import Time
        import astropy.units as u_

        flux_jy = 4.0
        stokes = np.zeros((4, 1, 1)); stokes[0, 0, 0] = flux_jy
        sky = pyradiosky.SkyModel(
            name=["bright_src"],
            ra=Longitude([343.5] * u_.deg),
            dec=Latitude([16.15] * u_.deg),
            stokes=stokes * u_.Jy,
            spectral_type="spectral_index",
            spectral_index=np.array([0.0]),
            reference_frequency=np.array([1.4e9]) * u_.Hz,
            frame="icrs",
        )
        h = _make_small_harness(noise_jy=0.0)
        t0 = Time("2026-01-25T22:26:05", format="isot", scale="utc")
        uv = h._build_uvdata(0, t0, sky)

        # All baselines at the phase centre: |V| = I/2 exactly
        expected = flux_jy / 2.0
        amp_xx = np.abs(uv.data_array[:, :, 0])
        amp_yy = np.abs(uv.data_array[:, :, 1])
        np.testing.assert_allclose(amp_xx, expected, rtol=1e-5,
                                   err_msg="XX amplitude mismatch for phase-center source")
        np.testing.assert_allclose(amp_yy, expected, rtol=1e-5,
                                   err_msg="YY amplitude mismatch for phase-center source")

    def test_spectral_index_applied(self, tmp_path):
        """A source with spectral index α=-1 should be fainter at higher frequencies."""
        import pyradiosky
        from astropy.coordinates import Longitude, Latitude
        from astropy.time import Time
        import astropy.units as u_

        ref_freq = 1.4e9
        alpha = -1.0
        stokes = np.zeros((4, 1, 1)); stokes[0, 0, 0] = 2.0
        sky = pyradiosky.SkyModel(
            name=["spectral_src"],
            ra=Longitude([343.5] * u_.deg),
            dec=Latitude([16.15] * u_.deg),
            stokes=stokes * u_.Jy,
            spectral_type="spectral_index",
            spectral_index=np.array([alpha]),
            reference_frequency=np.array([ref_freq]) * u_.Hz,
            frame="icrs",
        )
        h = _make_small_harness(n_antennas=4, n_integrations=2, noise_jy=0.0)
        t0 = Time("2026-01-25T22:26:05", format="isot", scale="utc")

        # Compare amplitude at first vs last channel
        uv = h._build_uvdata(0, t0, sky)
        amp_ch0  = np.abs(uv.data_array[0, 0,  0])   # lowest freq
        amp_chN  = np.abs(uv.data_array[0, -1, 0])   # highest freq in subband

        freqs = h.subband_freqs(0)
        expected_ratio = (freqs[-1] / freqs[0]) ** alpha
        observed_ratio = amp_chN / amp_ch0
        np.testing.assert_allclose(observed_ratio, expected_ratio, rtol=1e-4,
                                   err_msg="Spectral index scaling incorrect")

    def test_two_sources_superpose_linearly(self, tmp_path):
        """Visibility of (sky_a + sky_b) should equal V(sky_a) + V(sky_b)."""
        import pyradiosky
        from astropy.coordinates import Longitude, Latitude
        from astropy.time import Time
        import astropy.units as u_

        h = _make_small_harness(n_antennas=4, n_integrations=2, noise_jy=0.0)
        t0 = Time("2026-01-25T22:26:05", format="isot", scale="utc")

        def make_sky(ra, flux):
            s = np.zeros((4, 1, 1)); s[0, 0, 0] = flux
            return pyradiosky.SkyModel(
                name=[f"src_{ra}"],
                ra=Longitude([ra] * u_.deg),
                dec=Latitude([16.15] * u_.deg),
                stokes=s * u_.Jy,
                spectral_type="spectral_index",
                spectral_index=np.array([0.0]),
                reference_frequency=np.array([1.4e9]) * u_.Hz,
                frame="icrs",
            )

        import copy
        sky_a = make_sky(343.5, 1.0)
        sky_b = make_sky(344.0, 2.0)
        sky_ab = copy.deepcopy(sky_a)
        sky_ab.concat(sky_b, inplace=True)

        uv_a  = h._build_uvdata(0, t0, sky_a)
        uv_b  = h._build_uvdata(0, t0, sky_b)
        uv_ab = h._build_uvdata(0, t0, sky_ab)

        sum_ab = uv_a.data_array + uv_b.data_array
        np.testing.assert_allclose(uv_ab.data_array, sum_ab, rtol=1e-5,
                                   err_msg="Superposition of two sources failed")


# ── Stage 7: spectral consistency ─────────────────────────────────────────────

class TestStage7SpectralConsistency:
    """Tests that spectral information is consistent across subbands."""

    def test_mean_amplitude_decreases_with_frequency_for_steep_spectrum(self, tmp_path):
        """For α=-2 sources, higher-frequency subbands should have lower mean amplitude."""
        import pyradiosky
        from astropy.coordinates import Longitude, Latitude
        from astropy.time import Time
        import astropy.units as u_

        h = _make_small_harness(n_antennas=4, n_integrations=2, noise_jy=0.0,
                                n_sky_sources=5, seed=77)

        # Override with a single steep-spectrum source at phase centre
        stokes = np.zeros((4, 1, 1)); stokes[0, 0, 0] = 10.0
        sky = pyradiosky.SkyModel(
            name=["steep"],
            ra=Longitude([343.5] * u_.deg),
            dec=Latitude([16.15] * u_.deg),
            stokes=stokes * u_.Jy,
            spectral_type="spectral_index",
            spectral_index=np.array([-2.0]),
            reference_frequency=np.array([1.4e9]) * u_.Hz,
            frame="icrs",
        )
        t0 = Time("2026-01-25T22:26:05", format="isot", scale="utc")

        mean_amps = []
        for sb in range(0, 16, 4):  # sample 4 subbands
            uv = h._build_uvdata(sb, t0, sky)
            mean_amps.append(np.abs(uv.data_array[:, :, 0]).mean())

        # Amplitudes should be strictly decreasing (higher sb = higher freq = lower flux)
        for i in range(len(mean_amps) - 1):
            assert mean_amps[i] > mean_amps[i + 1], (
                f"Amplitude did not decrease from sb {i*4} to {(i+1)*4}: "
                f"{mean_amps[i]:.4f} vs {mean_amps[i+1]:.4f}"
            )


# ── Stage 8: simulation metrics ───────────────────────────────────────────────

class TestStage8SimulationMetrics:
    """Tests for the cloud-safe simulation metrics module."""

    def test_flux_recovery_error_perfect(self):
        from dsa110_continuum.simulation.metrics import flux_recovery_error
        assert flux_recovery_error(1.0, 1.0) == pytest.approx(0.0)

    def test_flux_recovery_error_10pct(self):
        from dsa110_continuum.simulation.metrics import flux_recovery_error
        assert flux_recovery_error(0.9, 1.0) == pytest.approx(-10.0)

    def test_flux_recovery_error_zero_injected(self):
        from dsa110_continuum.simulation.metrics import flux_recovery_error
        assert np.isnan(flux_recovery_error(1.0, 0.0))

    def test_astrometric_offset_zero(self):
        from dsa110_continuum.simulation.metrics import astrometric_offset
        offset = astrometric_offset(188.0, 42.0, 188.0, 42.0)
        assert offset == pytest.approx(0.0, abs=1e-9)

    def test_astrometric_offset_one_arcsec_approx(self):
        from dsa110_continuum.simulation.metrics import astrometric_offset
        # 1 arcsec = 1/3600 deg
        offset = astrometric_offset(188.0 + 1.0/3600, 42.0, 188.0, 42.0)
        # At dec=42°, 1 arcsec in RA corresponds to cos(42°)/cos(42°) = 1 arcsec separation
        # astropy gives great-circle separation
        assert 0.5 < offset < 2.0  # within 0.5–2 arcsec (generous, cos-projection)

    def test_detection_completeness_perfect(self):
        from dsa110_continuum.simulation.metrics import detection_completeness
        assert detection_completeness(50, 50) == pytest.approx(1.0)

    def test_detection_completeness_96pct(self):
        from dsa110_continuum.simulation.metrics import detection_completeness
        assert detection_completeness(48, 50) == pytest.approx(0.96)

    def test_detection_completeness_zero_injected(self):
        from dsa110_continuum.simulation.metrics import detection_completeness
        assert np.isnan(detection_completeness(0, 0))


# ── Stage 9: DSA-110 site and phase centre ─────────────────────────────────────

class TestStage9SiteAndPhaseCenter:
    """Tests for OVRO site and canary tile phase centre metadata."""

    def test_ovro_location_latitude(self):
        from dsa110_continuum.simulation.harness import _OVRO_LAT_DEG
        np.testing.assert_allclose(_OVRO_LAT_DEG, 37.2339, atol=0.001)

    def test_ovro_location_longitude(self):
        from dsa110_continuum.simulation.harness import _OVRO_LON_DEG
        np.testing.assert_allclose(_OVRO_LON_DEG, -118.2825, atol=0.001)

    def test_phase_center_ra_in_catalog(self, tmp_path):
        h = _make_small_harness()
        p = tmp_path / "phc.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        cat = uv.phase_center_catalog[0]
        np.testing.assert_allclose(
            np.degrees(cat["cat_lon"]), h.pointing_ra_deg, atol=0.01
        )

    def test_phase_center_dec_in_catalog(self, tmp_path):
        h = _make_small_harness()
        p = tmp_path / "phc.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        cat = uv.phase_center_catalog[0]
        np.testing.assert_allclose(
            np.degrees(cat["cat_lat"]), h.pointing_dec_deg, atol=0.01
        )

    def test_canary_tile_epoch_in_time_array(self, tmp_path):
        """Default start time should be the canary tile 2026-01-25T22:26:05."""
        from astropy.time import Time
        h = _make_small_harness()
        p = tmp_path / "canary.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        expected_jd = Time("2026-01-25T22:26:05", format="isot", scale="utc").jd
        actual_min_jd = float(uv.time_array.min())
        assert abs(actual_min_jd - expected_jd) < 1.0 / 86400.0  # within 1 second

    def test_custom_pointing_ra_dec(self, tmp_path):
        """Custom pointing direction should be recorded in the phase center catalog."""
        custom_ra, custom_dec = 10.5, -25.3
        h = SimulationHarness(
            n_antennas=4, n_integrations=2, seed=1,
            pointing_ra_deg=custom_ra, pointing_dec_deg=custom_dec,
        )
        p = tmp_path / "custom_phc.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        cat = uv.phase_center_catalog[0]
        np.testing.assert_allclose(np.degrees(cat["cat_lon"]), custom_ra, atol=0.01)
        np.testing.assert_allclose(np.degrees(cat["cat_lat"]), custom_dec, atol=0.01)


# ── Slow / expensive tests ────────────────────────────────────────────────────

@pytest.mark.slow
class TestSlow:
    """Full-scale tests skipped in normal CI. Run with: pytest --run-slow"""

    def test_full_96_antenna_subband(self, tmp_path):
        """Generate a realistic 96-antenna, 24-integration UVH5 subband."""
        h = SimulationHarness(n_antennas=96, n_integrations=24, n_sky_sources=50,
                              noise_jy=1.0, seed=0)
        p = tmp_path / "full96.uvh5"
        h.generate_subband(0, p)
        uv = h.load_subband(p)
        n_bls = 96 * 95 // 2  # = 4560
        assert uv.Nbls == n_bls
        assert uv.Ntimes == 24

    def test_all_16_subbands_closure(self, tmp_path):
        """All 16 subbands should pass closure with a small noiseless array."""
        h = SimulationHarness(n_antennas=6, n_integrations=3, noise_jy=0.0, seed=0)
        for sb in range(_N_SUBBANDS):
            p = tmp_path / f"full_cl_sb{sb:02d}.uvh5"
            h.generate_subband(sb, p)
            result = h.check_closure(p, n_triangles=10)
            assert result["passed"], f"SB{sb} closure failed"
