"""Bandpass and gain plot generation for calibration quality assessment."""

import logging
import os

logger = logging.getLogger(__name__)


def generate_bandpass_plots(
    bpcal_table: str,
    output_dir: str | None = None,
    plot_amplitude: bool = True,
    plot_phase: bool = True,
) -> list[str]:
    """Generate bandpass amplitude and phase plots using CASA plotbandpass.

    Generates per-SPW plots showing amplitude and phase vs frequency for all antennas.
    Plots are saved as PNG files suitable for dashboard display.

    Parameters
    ----------
    bpcal_table :
        Path to bandpass calibration table
    output_dir :
        Directory to save plots (default: same directory as table)
    plot_amplitude :
        Generate amplitude plots (default: True)
    plot_phase :
        Generate phase plots (default: True)

    Returns
    -------
        List of generated plot file paths

    Raises
    ------
    RuntimeError
        If plot generation fails

    """

    # Helper to call plotbandpass with CASA log environment protection
    def _call_plotbandpass(**kwargs):
        from dsa110_contimg.core.calibration.casa_service import CASAService

        service = CASAService()
        return service.plotbandpass(**kwargs)

    if output_dir is None:
        output_dir = os.path.dirname(bpcal_table) or "."

    # Create output directory if needed
    os.makedirs(output_dir, exist_ok=True)

    # Base filename from table name
    table_basename = os.path.basename(bpcal_table.rstrip("/"))
    plot_prefix = os.path.join(output_dir, f"{table_basename}_plot")

    generated_plots = []

    try:
        if plot_amplitude:
            amp_plot = f"{plot_prefix}_amp"
            _call_plotbandpass(
                caltable=bpcal_table,
                xaxis="freq",
                yaxis="amp",
                figfile=amp_plot,
                interactive=False,
                showflagged=False,
                overlay="antenna",
                plotrange=[0, 0, 0, 0],  # Auto range
            )
            # CASA generates multiple files (per SPW), find them
            amp_files = _find_generated_plots(amp_plot)
            generated_plots.extend(amp_files)
            logger.info(f"Generated {len(amp_files)} amplitude plot(s)")

        if plot_phase:
            phase_plot = f"{plot_prefix}_phase"
            _call_plotbandpass(
                caltable=bpcal_table,
                xaxis="freq",
                yaxis="phase",
                figfile=phase_plot,
                interactive=False,
                showflagged=False,
                overlay="antenna",
                plotrange=[0, 0, -180, 180],  # Phase range
            )
            # CASA generates multiple files (per SPW), find them
            phase_files = _find_generated_plots(phase_plot)
            generated_plots.extend(phase_files)
            logger.info(f"Generated {len(phase_files)} phase plot(s)")

        logger.info(
            f":check: Bandpass plots generated: {len(generated_plots)} file(s) in {output_dir}"
        )
        return generated_plots

    except Exception as e:
        logger.error(f"Failed to generate bandpass plots: {e}")
        raise RuntimeError(f"Bandpass plot generation failed: {e}") from e


def _find_generated_plots(plot_prefix: str) -> list[str]:
    """Find all plot files generated by CASA plotbandpass.

    CASA generates multiple files with suffixes like .spw00.t00.png, .spw01.t00.png, etc.

    Parameters
    ----------
    plot_prefix :
        Base prefix used for plot files

    Returns
    -------
        List of full paths to generated plot files

    """
    plot_dir = os.path.dirname(plot_prefix) or "."
    plot_basename = os.path.basename(plot_prefix)

    generated = []
    if os.path.exists(plot_dir):
        for filename in os.listdir(plot_dir):
            if filename.startswith(plot_basename) and filename.endswith(".png"):
                generated.append(os.path.join(plot_dir, filename))

    return sorted(generated)


def generate_gain_plots(
    gcal_table: str,
    output_dir: str | None = None,
    plot_amplitude: bool = True,
    plot_phase: bool = True,
) -> list[str]:
    """Generate gain calibration amplitude and phase plots using CASA plotcal.

    Generates plots showing amplitude and phase vs time for all antennas.
    Plots are saved as PNG files suitable for dashboard display.

    Parameters
    ----------
    gcal_table :
        Path to gain calibration table
    output_dir :
        Directory to save plots (default: same directory as table)
    plot_amplitude :
        Generate amplitude plots (default: True)
    plot_phase :
        Generate phase plots (default: True)

    Returns
    -------
        List of generated plot file paths

    Raises
    ------
    RuntimeError
        If plot generation fails

    """

    # Helper to call plotcal with CASA log environment protection
    def _call_plotcal(**kwargs):
        from dsa110_contimg.core.calibration.casa_service import CASAService

        service = CASAService()
        return service.plotcal(**kwargs)

    if output_dir is None:
        output_dir = os.path.dirname(gcal_table) or "."

    # Create output directory if needed
    os.makedirs(output_dir, exist_ok=True)

    # Base filename from table name
    table_basename = os.path.basename(gcal_table.rstrip("/"))
    plot_prefix = os.path.join(output_dir, f"{table_basename}_plot")

    generated_plots = []

    try:
        if plot_amplitude:
            amp_plot = f"{plot_prefix}_amp"
            _call_plotcal(
                caltable=gcal_table,
                xaxis="time",
                yaxis="amp",
                figfile=amp_plot,
                interactive=False,
                showflagged=False,
                overlay="antenna",
                plotrange=[0, 0, 0, 0],  # Auto range
            )
            # CASA generates multiple files (per SPW), find them
            amp_files = _find_generated_plots(amp_plot)
            generated_plots.extend(amp_files)
            logger.info(f"Generated {len(amp_files)} gain amplitude plot(s)")

        if plot_phase:
            phase_plot = f"{plot_prefix}_phase"
            _call_plotcal(
                caltable=gcal_table,
                xaxis="time",
                yaxis="phase",
                figfile=phase_plot,
                interactive=False,
                showflagged=False,
                overlay="antenna",
                plotrange=[0, 0, -180, 180],  # Phase range
            )
            # CASA generates multiple files (per SPW), find them
            phase_files = _find_generated_plots(phase_plot)
            generated_plots.extend(phase_files)
            logger.info(f"Generated {len(phase_files)} gain phase plot(s)")

        logger.info(f":check: Gain plots generated: {len(generated_plots)} file(s) in {output_dir}")
        return generated_plots

    except Exception as e:
        logger.error(f"Failed to generate gain plots: {e}")
        raise RuntimeError(f"Gain plot generation failed: {e}") from e
